server:
  port: 8090
dubbo:
  application:
    name: consumer
    qos-accept-foreign-ip: false
    qos-enable: true
    qos-port: 33333
  registry:
    address: zookeeper://192.168.238.129:2181 #192.168.1.105:2181
  consumer:
    timeout: 5000

spring:
  redis:
      database: 0
      host: 192.168.238.129
      port: 6379
      password:
  #    cluster:
  #      nodes:
  #       - 192.168.238.129:7001
  #       - 192.168.238.129:7002
  #       - 192.168.238.129:7003
  #       - 192.168.238.129:7004
  #       - 192.168.238.129:7005
  #       - 192.168.238.129:7006
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 1000ms